# Generated by Django 5.1.3 on 2024-11-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
